version: '3'
services:
    nginx:
    	 image: nginx:1.21.0
	 ports:
	     - "443:80"
	 volumes:
	     - ./nginx.conf:/etc/nginx/conf.d/default.conf
	     - ./app:/app
    postgres_db:
	 image: postgres:lastest
         containter_name: postgres
	 environment:
	     - POSTGRES_USER = admin
             - POSTGRES_PASSWORD = "password1"
             - POSTGRES_DB = MY_database
    	 ports:
	     - "443:80"
